companyHR/Controllers/EmployeesVacationController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using RepositoryUsingEFinMVC.GenericRepository;

namespace companyHR.Controllers
{
    public class EmployeesVacationController : Controller
    {
        private IGenericRepository<employeesVacation> employeesVacationRep;

        private readonly IMapper _mapper;
        public EmployeesVacationController(IGenericRepository<employeesVacation> _EmployeesVacation, IMapper mapper)
        {

            this.employeesVacationRep = _EmployeesVacation;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data = employeesVacationRep.GetAll(p => p.vacation, p => p.employee);
            var model = _mapper.Map<IEnumerable<EmployeesVacationVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]

        public IActionResult Create(EmployeesVacationVM model)
        {
            try
            {
                ModelState.Remove("vacation");
                ModelState.Remove("employee");
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<employeesVacation>(model);
                    employeesVacationRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = employeesVacationRep.GetById(id, p => p.vacation, p => p.employee);
            var model = _mapper.Map<EmployeesVacationVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = employeesVacationRep.GetById(id);
            var model = _mapper.Map<EmployeesVacationVM>(data);

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult edit(EmployeesVacationVM model)
        {
            try
            {
                return editEmployeesVacation(model);
            }
            catch
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = employeesVacationRep.GetById(id, p => p.vacation, p => p.employee);
            var model = _mapper.Map<EmployeesVacationVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(EmployeesVacationVM model)
        {

            try
            {
                var data = _mapper.Map<employeesVacation>(model);
                employeesVacationRep.Delete(data);

                return RedirectToAction("Index");


            }
            catch
            {
                return View();

            }
        }




        private IActionResult editEmployeesVacation(EmployeesVacationVM model)
        {
            ModelState.Remove("vacation");
            ModelState.Remove("employee");
            if (ModelState.IsValid)
            {

                var data = _mapper.Map<employeesVacation>(model);
                employeesVacationRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
    }
}

companyHR/Views/EmployeesVacation/Create.cshtml
@model company.BL.Model.EmployeesVacationVM


@{
    ViewBag.Title = "Add Employee Vacation";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Add Employee Vacation</h2>
               
            </div>
            <div class="body">
                <form id="form_validation" asp-asp-controller="EmployeesVacation" asp-action="create" method="post">

                    <div class="row">

                        <div class="form-group form-float">
                            <div class="form-line ">

                                <select id="employeeId" asp-for="employeeId" class="form-control show-tick">
                             
                            </select>
                            <br />
                            <label class="form-label"> From Date </label>

                            </div>                  
                            <span asp-validation-for="employeeId" class="text-danger "></span>

                        </div>

                        <div class="form-group form-float">
                        <div class="form-group form-float">
                                <select asp-for="vacationId" id="vacationId" class="form-control show-tick">
                                    <option value="">-- Please select Bonus/Deduction  --</option>
                                   
                            </select>

                                <span asp-validation-for="vacationId" class="text-danger "></span>
                        </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" onfocus="(this.type='date')" onblur="if(!this.value)this.type='text'" asp-for="fromDate" />
                                    <label class="form-label"> From Date </label>
                                    <span asp-validation-for="fromDate" class="text-danger "></span>

                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" onfocus="(this.type='date')" onblur="if(!this.value)this.type='text'" asp-for="toDate" />
                                    <label class="form-label"> To Date </label>
                                    <span asp-validation-for="toDate" class="text-danger "></span>

                                </div>
                            </div>
                    </div>
   
                </div>

                    <button class="btn btn-primary waves-effect" type="submit">Create</button>
                    <button class="btn btn-primary waves-effect" type="reset">Cancel</button>
                    <a asp-controller="EmployeesVacation" asp-action="index" class="btn btn-success">Back</a>


                </form>
            </div>
        </div>
    </div>
</div>


@section MicrosoftValidation{
    <script>

        $(function () {

            $("#employeeId").empty();
            $("#employeeId").append("<option value='0'>Choose Employee</option>");
            $.ajax({
                type: "POST",
                url: "/Employees/getAllEmployee",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#employeeId").append("<option value='" + e.id + "'>" + e.employeeName + "</option>");
                    });
                }
            });


            $("#vacationId").empty();
            $("#vacationId").append("<option value='0'>Choose Vacation</option>");
            $.ajax({
                type: "POST",
                url: "/Vacation/getAllVacation",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#vacationId").append("<option value='" + e.id + "'>" + e.vacationName + "</option>");
                    });
                }
            });
        });
    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

companyHR/Views/EmployeesVacation/Index.cshtml
@model IEnumerable<company.BL.Model.EmployeesVacationVM>
@{
    ViewBag.Title = "Employee Bonus";
}

<!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <div class="row ">
                    <div class="col-lg-6 text-left-center ">
                        <h2>
                            Employees Vacation Table
                        </h2>
                    </div>
                  
                    <div class="col-lg-6 text-right-center">
                        <a class=" btn btn-primary " asp-controller="EmployeesVacation" asp-action="Create">Create</a>
                    </div>

                </div>
                 
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Employee Name</th>
                                <th> vacation Name</th>
                                <th>vacation Cost</th>
                                <th> From Date</th>
                                <th>To Date</th>
                                <th>DETAILS</th>
                                <th>EDIT</th>
                                <th>DELETE</th>

                            </tr>
                        </thead>
                       
                        <tbody>
                            @foreach(var  item  in Model)
                            {
                               


                                <tr >
                                    <td> @item.id</td>
                                     <td>@item.employee.employeeName</td>
                                     <td>@item.vacation.vacationName</td>
                                     <td>@item.vacation.vacationCost</td>
                                     <td>@item.fromDate</td>
                                     <td>@item.toDate</td>


                                    <td><a asp-controller="EmployeesVacation" asp-action="details" asp-route-id="@item.id" class="btn btn-info">Details</a></td>
                                    <td><a asp-controller="EmployeesVacation" asp-action="edit" asp-route-id="@item.id" class="btn btn-warning">Edit</a></td>
                                    <td><a asp-controller="EmployeesVacation" asp-action="delete" asp-route-id="@item.id" class="btn btn-danger">Delete</a></td>

                                 </tr>
                            }

                        </tbody>
                       
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->
<!-- Jquery DataTable Plugin Js -->
 
@section DataTabelScripts {
       
    <script src="~/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="~/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
    <script src="~/js/pages/tables/jquery-datatable.js"></script>

    }
   

companyHR/Views/EmployeesVacation/delete.cshtml
@model company.BL.Model.EmployeesVacationVM
@* @inject company.BL.Interface.IEmployeeRep employeeRep
@inject company.BL.Interface.IVacationRep vactionRep *@


@{
    ViewBag.Title = "Delete Employee Vacation";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Delete Employee Vacation</h2>

            </div>
            <div class="body">
                <form id="form_validation" asp-asp-controller="EmployeesVacation" asp-action="Delete" method="post">

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" asp-for="employee.employeeName" readonly="readonly" />
                                    <label class="form-label">Employee Name </label>

                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" asp-for="vacation.vacationName" readonly="readonly" />
                                    <label class="form-label">Vacation Name</label>

                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" asp-for="vacation.vacationCost" readonly="readonly" />
                                    <label class="form-label">Vacation Cost</label>

                                </div>
                            </div>


                        </div>
                    </div>

                    <button class="btn btn-primary waves-effect" type="submit">Delete</button>
                    <a asp-controller="EmployeesVacation" asp-action="index" class="btn btn-success">Back</a>


                </form>
            </div>
        </div>
    </div>
</div>

companyHR/Views/EmployeesVacation/details.cshtml
@model company.BL.Model.EmployeesVacationVM

@{
    ViewBag.Title = "Employee Vacation Details";
}


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2> Employee Vacation Details </h2>

            </div>
            <div class="body">

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group form-float">
                                <div class="form-line">
                                <input type="text" class="form-control" asp-for="employee.employeeName" readonly="readonly" />
                                    <label class="form-label">Employee Name </label>

                                </div>
                            </div> 
                             <div class="form-group form-float">
                                <div class="form-line">
                                <input type="text" class="form-control" asp-for="vacation.vacationName" readonly="readonly" />
                                <label class="form-label">Vacation Name</label>

                                </div>
                            </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" class="form-control" asp-for="vacation.vacationCost"   readonly="readonly" />
                                <label class="form-label">Vacation Cost</label>

                            </div>
                        </div> 

                         
                        </div> 
                        </div>
                <a asp-controller="EmployeesVacation" asp-action="index" class="btn btn-success">Back</a>
                    </div>
            </div>
        </div>
    </div>

companyHR/Views/EmployeesVacation/edit.cshtml
@model company.BL.Model.EmployeesVacationVM


@{
    ViewBag.Title = "Edit Employee Vacation";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Edit Employee Vacation</h2>

            </div>
            <div class="body">
                <form id="form_validation" asp-asp-controller="EmployeesVacation" asp-action="Edit" method="post">
                    @Html.AntiForgeryToken()
                    <div class="row">

                        <div class="form-group form-float">
                            <div class="form-line ">

                                <select id="employeeId" asp-for="employeeId" class="form-control show-tick">
                                </select>
                                <br />
                                <label class="form-label"> Employees  </label>

                            </div>
                            <span asp-validation-for="employeeId" class="text-danger "></span>

                        </div>

                        <div class="form-group ">
                            <div class="form-group form-float form-line ">
                                <select asp-for="vacationId" id="vacationId" class="form-control show-tick">
                                    <option value="">-- Please select Bonus/Deduction  --</option>

                                </select>
                                <label class="form-label"> vacation </label>

                                <span asp-validation-for="vacationId" class="text-danger "></span>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="date" class="form-control"  asp-for="fromDate" />
                                    <label class="form-label"> From Date </label>
                                    <span asp-validation-for="fromDate" class="text-danger "></span>

                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="date" class="form-control"  asp-for="toDate" />
                                    <label class="form-label"> To Date </label>
                                    <span asp-validation-for="toDate" class="text-danger "></span>

                                </div>
                            </div>
                        </div>

                    </div>

                    <button class="btn btn-warning waves-effect" type="submit">Edit</button>
                    <button class="btn btn-primary waves-effect" type="reset">Cancel</button>
                    <a asp-controller="EmployeesVacation" asp-action="index" class="btn btn-success">Back</a>


                </form>
            </div>
        </div>
    </div>
</div>


@section MicrosoftValidation{
    <script>

        $(function () {

            $("#employeeId").empty();
            $("#employeeId").append("<option value='0'>Choose Employee</option>");
            $.ajax({
                type: "POST",
                url: "/Employees/getAllEmployee",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#employeeId").append("<option value='" + e.id + "'>" + e.employeeName + "</option>");
                    });
                    $("#employeeId").val(@Model.employeeId);

                }
            });
       



            $("#vacationId").empty();
            $("#vacationId").append("<option value='0'>Choose Vacation</option>");
            $.ajax({
                type: "POST",
                url: "/Vacation/getAllVacation",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#vacationId").append("<option value='" + e.id + "'>" + e.vacationName + "</option>");
                    });
                    $("#vacationId").val(@Model.vacationId);

                }
            });


        });

        $(document).ready(function () {
            $(document).ready(() => {
            });
        });

    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}