companyHR/Controllers/DepartmentController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using RepositoryUsingEFinMVC.GenericRepository;

namespace companyHR.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IMapper _mapper;
        private IGenericRepository<Department> departmentRep;
        public DepartmentController(IGenericRepository<Department> _departmentRep, IMapper mapper)
        {
            this.departmentRep = _departmentRep;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data= departmentRep.GetAll();
            var model = _mapper.Map<IEnumerable<DepartmentVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create() 
        { 
        
          return View();
        }
        [HttpPost]
        public IActionResult Create(DepartmentVM  model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<Department>(model);
                    departmentRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id) 
        {
         var data= departmentRep.GetById(id);
            var model = _mapper.Map<DepartmentVM>(data);
          return View(model);
        }        
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = departmentRep.GetById(id);
            var model = _mapper.Map<DepartmentVM>(data);

            return View(model);
        }

        [HttpPost]
        public IActionResult edit(DepartmentVM model)
        {
            try
            {
                return editDepartment(model);
            }
            catch
            {
                return View(model);
            }

        }
        [HttpGet]
        public IActionResult delete(int id) 
        {
            var data = departmentRep.GetById(id);
            var model = _mapper.Map<DepartmentVM>(data);

            return View(model);
        }    
        [HttpPost]
        public IActionResult delete(DepartmentVM model) 
        {

            try
            {
                var data = _mapper.Map<Department>(model);
                    departmentRep.Delete(data.Id);

                    return RedirectToAction("Index");
               

            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Not Deleted");

                return View(model);

            }
        }
        private IActionResult editDepartment(DepartmentVM model)
        {
            if (ModelState.IsValid)
            {
                var data = _mapper.Map<Department>(model);
                departmentRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public JsonResult getAllDepartment()
        {
            var data = departmentRep.GetAll().Select(o => new { o.Id, o.Name }).ToList();

            return Json(data);
        }
    }
}

companyHR/Controllers/EmployeeBonusController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using RepositoryUsingEFinMVC.GenericRepository;

namespace companyHR.Controllers
{
    public class EmployeeBonusController : Controller
    {
        private IGenericRepository<employeesBonu> employeeBounsRep;

        private readonly IMapper _mapper;
        public EmployeeBonusController(IGenericRepository<employeesBonu> _employeeBounsRep, IMapper mapper)
        {

            this.employeeBounsRep = _employeeBounsRep;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data = employeeBounsRep.GetAll(p=>p.bonus,page=>page.employee);
            var model = _mapper.Map<IEnumerable<EmployeeBounsVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeBounsVM model)
        {
            try
            {
                ModelState.Remove("bonus");
                ModelState.Remove("employee");
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<employeesBonu>(model);
                    employeeBounsRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = employeeBounsRep.GetById(id, p => p.bonus, page => page.employee);
            var model = _mapper.Map<EmployeeBounsVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = employeeBounsRep.GetById(id);
            var model = _mapper.Map<EmployeeBounsVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult edit(EmployeeBounsVM model)
        {
            try
            {
                return editEmployeeBouns(model);
            }
            catch
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = employeeBounsRep.GetById(id, p => p.bonus, page => page.employee);
            var model = _mapper.Map<EmployeeBounsVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(EmployeeBounsVM model)
        {

            try
            {
                var data = _mapper.Map<employeesBonu>(model);
                employeeBounsRep.Delete(data.id);

                return RedirectToAction("Index");


            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Not Deleted");
                return View(model);

            }
        }




        private IActionResult editEmployeeBouns(EmployeeBounsVM model)
        {
            ModelState.Remove("bonus");
            ModelState.Remove("employee");
            if (ModelState.IsValid)
            {

                var data = _mapper.Map<employeesBonu>(model);
                employeeBounsRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

    }
}

companyHR/Controllers/EmployeesController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using RepositoryUsingEFinMVC.GenericRepository;
using System;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace companyHR.Controllers
{
    public class EmployeesController : Controller
    {

        private readonly IMapper _mapper;
        private IGenericRepository<employee> employeeRep;
        public EmployeesController(IGenericRepository<employee> _employeeRep, IMapper mapper)
        {

            this.employeeRep = _employeeRep;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data = GetData();
            var model = _mapper.Map<IEnumerable<EmployeeVM>>(data);
            return View(model);
        }

        private IEnumerable<employee> GetData()
        {
            return employeeRep.GetAll(p => p.deprtment, p => p.gender, P => P.religion,p=>p.job);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeVM model)
        {
            try
            {
                removeValidationFromModel();
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<employee>(model);
                    employeeRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = employeeRep.GetById(id,P=>P.job,P=>P.gender,P => P.religion);
            var model = _mapper.Map<EmployeeVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = employeeRep.GetById(id);
            var model = _mapper.Map<EmployeeVM>(data);

            return View(model);
        }

        [HttpPost]
        public IActionResult edit(EmployeeVM model)
        {
            try
            {
                return editEmployee(model);
            }
            catch 
            {
                return View(model);
            }

        }
        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = employeeRep.GetById(id, P => P.job, P => P.gender, P => P.religion);
            var model = _mapper.Map<EmployeeVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(EmployeeVM model)
        {

            try
            {
                var data = _mapper.Map<employee>(model);
                employeeRep.Delete(data.id);

                return RedirectToAction("Index");


            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Not Deleted");
                return View(model);

            }
        }
        private IActionResult editEmployee( EmployeeVM model)
        {
            removeValidationFromModel();

            if (ModelState.IsValid)
            {
                var data = _mapper.Map<employee>(model);
                employeeRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }

        }
        void removeValidationFromModel()
        {
            ModelState.Remove("deprtment");
            ModelState.Remove("religion");
            ModelState.Remove("gender");
        }
        [HttpPost]
        public JsonResult getAllEmployee()
        {
            var data = employeeRep.GetAll().Select(o => new {o.id,o.employeeName}).ToList();

            return Json(data);
        }


    

    }
}

companyHR/Views/EmployeeBonus/Create.cshtml
@model company.BL.Model.EmployeeBounsVM


@{
    ViewBag.Title = "Add Employee Vacation";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Add Employee Vacation</h2>
               
            </div>
            <div class="body">
                <form id="form_validation" asp-asp-controller="EmployeeBonus" asp-action="create" method="post">

                    <div class="row">

                        <div class="form-group form-float">
                            <div class="form-line ">

                                <select id="employeeId" asp-for="employeeId" class="form-control show-tick">
                             
                            </select>
                            <br />
                            <label class="form-label"> From Date </label>

                            </div>                  
                            <span asp-validation-for="employeeId" class="text-danger "></span>

                        </div>

                        <div class="form-group form-float">
                        <div class="form-group form-float">
                                <select asp-for="bonusId" id="bonusId" class="form-control show-tick">
                                    <option value="">-- Please select Bonus/Deduction  --</option>
                                   
                            </select>

                                <span asp-validation-for="bonusId" class="text-danger "></span>
                        </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" onfocus="(this.type='date')" onblur="if(!this.value)this.type='text'" asp-for="date" />
                                    <label class="form-label">  Date </label>
                                    <span asp-validation-for="date" class="text-danger "></span>

                                </div>
                            </div>

                    </div>
   
                </div>

                    <button class="btn btn-primary waves-effect" type="submit">Create</button>
                    <button class="btn btn-primary waves-effect" type="reset">Cancel</button>
                    <a asp-controller="EmployeeBonus" asp-action="index" class="btn btn-success">Back</a>


                </form>
            </div>
        </div>
    </div>
</div>


@section MicrosoftValidation{
    <script>

        $(function () {

            $("#employeeId").empty();
            $("#employeeId").append("<option value='0'>Choose Employee</option>");
            $.ajax({
                type: "POST",
                url: "/Employees/getAllEmployee",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#employeeId").append("<option value='" + e.id + "'>" + e.employeeName + "</option>");
                    });
                }
            });


            $("#bonusId").empty();
            $("#bonusId").append("<option value='0'>Choose Bonus</option>");
            $.ajax({
                type: "POST",
                url: "/Bonuss/getAllbonuses",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#bonusId").append("<option value='" + e.id + "'>" + e.bonusName + "</option>");
                    });
                }
            });
        });
    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

companyHR/Views/EmployeeBonus/Index.cshtml
@model IEnumerable<company.BL.Model.EmployeeBounsVM>
@{
    ViewBag.Title = "Employee Bonus";
}

<!-- Exportable Table -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <div class="row ">
                    <div class="col-lg-6 text-left-center ">
                        <h2>
                            Employee Bonus Table
                        </h2>
                    </div>
                  
                    <div class="col-lg-6 text-right-center">
                        <a class=" btn btn-primary " asp-controller="EmployeeBonus" asp-action="Create">Create</a>
                    </div>

                </div>
                 
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Employee Name</th>
                                <th> bonusName</th>
                                <th>bonusValue</th>
                                <th> Bonus/Deduction</th>
                                <th>bonusDate</th>
                                <th>DETAILS</th>
                                <th>EDIT</th>
                                <th>DELETE</th>

                            </tr>
                        </thead>
                       
                        <tbody>
                            @foreach(var  item  in Model)
                            {
                                string style = item.bonus.Bonusflag == false ? "color:Red" : "color:black";


                                <tr style="@style">
                                    <td> @item.id</td>
                                     <td>@item.employee.employeeName</td>
                                     <td>@item.bonus.bonusName</td>
                                     <td>@item.bonus.bonusValue</td>
                                    @{
                                        if (@item.bonus.Bonusflag == true)
                                        {
                                            <td>Bonus</td>
                                        }
                                        else
                                        {
                                            <td>Deduction</td>
                                        }
                                    }
                                     <td>@item.date</td>


                                    <td><a asp-controller="EmployeeBonus" asp-action="details" asp-route-id="@item.id" class="btn btn-info">Details</a></td>
                                    <td><a asp-controller="EmployeeBonus" asp-action="edit" asp-route-id="@item.id" class="btn btn-warning">Edit</a></td>
                                    <td><a asp-controller="EmployeeBonus" asp-action="delete" asp-route-id="@item.id" class="btn btn-danger">Delete</a></td>

                                 </tr>
                            }

                        </tbody>
                       
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #END# Exportable Table -->
<!-- Jquery DataTable Plugin Js -->
 
@section DataTabelScripts {
       
    <script src="~/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="~/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="~/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
    <script src="~/js/pages/tables/jquery-datatable.js"></script>

    }
   

companyHR/Views/EmployeeBonus/delete.cshtml
@model company.BL.Model.EmployeeBounsVM
@inject company.BL.Interface.IReligionRep religinRep
@inject company.BL.Interface.IGenderRep genderRep

@{
    ViewBag.Title = "Delete Employee";
    // var x = emplo.GetAll();
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Delete Employee</h2>

            </div>
            <div class="body">
                <form id="form_validation" asp-asp-controller="Department" asp-action="delete" method="post">

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" asp-for="employee.employeeName" readonly="readonly" />
                                    <label class="form-label">Employee Name </label>

                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" asp-for="bonus.bonusName" readonly="readonly" />
                                    <label class="form-label">Bonus Name</label>

                                </div>
                            </div>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" asp-for="bonus.bonusValue" readonly="readonly" />
                                    <label class="form-label">Vacation Cost</label>

                                </div>
                            </div>


                        </div>
                    </div>
                    <button class="btn btn-primary waves-effect" type="submit">Delete</button>
                    <button class="btn btn-primary waves-effect" type="reset">Cancel</button>
                    <a asp-controller="Employees" asp-action="index" class="btn btn-success">Back</a>


                </form>
            </div>
        </div>
    </div>
</div>
@section MicrosoftValidation{

    <script>

        $(function () {

            $("#deprtmentId").empty();
            $("#deprtmentId").append("<option value='0'>Choose Department</option>");
            $.ajax({
                type: "GET",
                url: "/Department/getAllDepartment",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#deprtmentId").append("<option value='" + e.id + "'>" + e.name + "</option>");
                    });
                }
            });
        });
    </script>


    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>


}

companyHR/Views/EmployeeBonus/details.cshtml
@model company.BL.Model.EmployeeBounsVM

@{
    ViewBag.Title = "Employee Bonus Details";
}


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2> Employee Bonus Details </h2>

            </div>
            <div class="body">

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group form-float">
                                <div class="form-line">
                                <input type="text" class="form-control" asp-for="employee.employeeName" readonly="readonly" />
                                    <label class="form-label">Employee Name </label>

                                </div>
                            </div> 
                             <div class="form-group form-float">
                                <div class="form-line">
                                <input type="text" class="form-control" asp-for="bonus.bonusName" readonly="readonly" />
                                    <label class="form-label">Bonus Name</label>

                                </div>
                            </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" class="form-control" asp-for="bonus.bonusValue"   readonly="readonly" />
                                <label class="form-label">Vacation Cost</label>

                            </div>
                        </div> 

                         
                        </div> 
                        </div>
                <a asp-controller="EmployeeBonus" asp-action="index" class="btn btn-success">Back</a>
                    </div>
            </div>
        </div>
    </div>

companyHR/Views/EmployeeBonus/edit.cshtml
@model company.BL.Model.EmployeeBounsVM


@{
    ViewBag.Title = "Edit Employee Bouns";
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Edit Employee Bouns</h2>

            </div>
            <div class="body">
                <form id="form_validation" asp-asp-controller="EmployeeBonus" asp-action="Edit" method="post">
                    @Html.AntiForgeryToken()
                    <div class="row">

                        <div class="form-group form-float">
                            <div class="form-line ">

                                <select id="employeeId" asp-for="employeeId" class="form-control show-tick">
                                </select>
                                <br />
                                <label class="form-label"> Employees  </label>

                            </div>
                            <span asp-validation-for="employeeId" class="text-danger "></span>

                        </div>

                        <div class="form-group ">
                            <div class="form-group form-float form-line ">
                                <select asp-for="bonusId" id="bonusId" class="form-control show-tick">
                                    <option value="">-- Please select Bonus/Deduction  --</option>

                                </select>
                                <label class="form-label"> vacation </label>

                                <span asp-validation-for="bonusId" class="text-danger "></span>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="date" class="form-control"  asp-for="date" />
                                    <label class="form-label">  Date </label>
                                    <span asp-validation-for="date" class="text-danger "></span>

                                </div>
                            </div>

                        </div>

                    </div>

                    <button class="btn btn-warning waves-effect" type="submit">Edit</button>
                    <button class="btn btn-primary waves-effect" type="reset">Cancel</button>
                    <a asp-controller="EmployeeBonus" asp-action="index" class="btn btn-success">Back</a>


                </form>
            </div>
        </div>
    </div>
</div>


@section MicrosoftValidation{
    <script>

        $(function () {

            $("#employeeId").empty();
            $("#employeeId").append("<option value='0'>Choose Employee</option>");
            $.ajax({
                type: "POST",
                url: "/Employees/getAllEmployee",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#employeeId").append("<option value='" + e.id + "'>" + e.employeeName + "</option>");
                    });
                    $("#employeeId").val(@Model.employeeId);

                }
            });




            $("#bonusId").empty();
            $("#bonusId").append("<option value='0'>Choose Bonus/Deduction</option>");
            $.ajax({
                type: "POST",
                url: "/Bonuss/getAllbonuses",
                data: {},
                success: function (res) {
                    console.log(res);
                    $.each(res, function (i, e) {
                        $("#bonusId").append("<option value='" + e.id + "'>" + e.bonusName + "</option>");
                    });
                    $("#bonusId").val(@Model.bonusId);

                }
            });


        });

        $(document).ready(function () {
            $(document).ready(() => {
            });
        });

    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}