companyHR/Controllers/BonussController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;
using RepositoryUsingEFinMVC.GenericRepository;

namespace companyHR.Controllers
{
    public class BonussController : Controller
    {
        private readonly IMapper _mapper;
        private IGenericRepository<bonuss> bonusRep;
        public BonussController(IGenericRepository<bonuss> _repository, IMapper mapper)
        {
            this.bonusRep = _repository;
            this._mapper = mapper;
        }
        
        public IActionResult Index()
        {
            var data = bonusRep.GetAll();
            var model = _mapper.Map<IEnumerable<BonusVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(BonusVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<bonuss>(model);
                    bonusRep.Insert(data);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = bonusRep.GetById(id);
            var model = _mapper.Map<BonusVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = bonusRep.GetById(id);
            var model = _mapper.Map<BonusVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult edit(BonusVM model)
        {
            try
            {
                return editBonus(model);
            }
            catch
            {
                return View(model);
            }
        }
        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = bonusRep.GetById(id);
            var model = _mapper.Map<BonusVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(BonusVM model)
        {
            try
            {
                var data = _mapper.Map<bonuss>(model);
                bonusRep.Delete(data.id);
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Not Deleted");
                return View(model);
            }
        }
        private IActionResult editBonus(BonusVM model)
        {
            if (ModelState.IsValid)
            {
                var data = _mapper.Map<bonuss>(model);
                bonusRep.Update(data);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        [HttpPost]
        public JsonResult getBonusById(int  id)
        {
            var data = bonusRep.GetById(id);
            var model = _mapper.Map<BonusVM>(data);
            return Json(model);
        }
        [HttpPost]
        public JsonResult getAllbonuses()
        {
            var data = bonusRep.GetAll().Select(o => new { o.id, o.bonusName }).ToList();

            return Json(data);
        }
    }
}

companyHR/Controllers/EmployeesController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using RepositoryUsingEFinMVC.GenericRepository;
using System;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace companyHR.Controllers
{
    public class EmployeesController : Controller
    {

        private readonly IMapper _mapper;
        private IGenericRepository<employee> employeeRep;
        public EmployeesController(IGenericRepository<employee> _employeeRep, IMapper mapper)
        {

            this.employeeRep = _employeeRep;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data = GetData();
            var model = _mapper.Map<IEnumerable<EmployeeVM>>(data);
            return View(model);
        }

        private IEnumerable<employee> GetData()
        {
            return employeeRep.GetAll(p => p.deprtment, p => p.gender, P => P.religion,p=>p.job);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeVM model)
        {
            try
            {
                removeValidationFromModel();
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<employee>(model);
                    employeeRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = employeeRep.GetById(id,P=>P.job,P=>P.gender,P => P.religion);
            var model = _mapper.Map<EmployeeVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = employeeRep.GetById(id);
            var model = _mapper.Map<EmployeeVM>(data);

            return View(model);
        }

        [HttpPost]
        public IActionResult edit(EmployeeVM model)
        {
            try
            {
                return editEmployee(model);
            }
            catch 
            {
                return View(model);
            }

        }
        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = employeeRep.GetById(id, P => P.job, P => P.gender, P => P.religion);
            var model = _mapper.Map<EmployeeVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(EmployeeVM model)
        {

            try
            {
                var data = _mapper.Map<employee>(model);
                employeeRep.Delete(data.id);

                return RedirectToAction("Index");


            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Not Deleted");
                return View(model);

            }
        }
        private IActionResult editEmployee( EmployeeVM model)
        {
            removeValidationFromModel();

            if (ModelState.IsValid)
            {
                var data = _mapper.Map<employee>(model);
                employeeRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }

        }
        void removeValidationFromModel()
        {
            ModelState.Remove("deprtment");
            ModelState.Remove("religion");
            ModelState.Remove("gender");
        }
        [HttpPost]
        public JsonResult getAllEmployee()
        {
            var data = employeeRep.GetAll().Select(o => new {o.id,o.employeeName}).ToList();

            return Json(data);
        }


    

    }
}

companyHR/Controllers/JobController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using RepositoryUsingEFinMVC.GenericRepository;

namespace companyHR.Controllers
{
    public class JobController : Controller
    {


        private readonly IMapper _mapper;
        private IGenericRepository<job> jobRep;
        public JobController(IGenericRepository<job> _jobRep, IMapper mapper)
        {

            this.jobRep = _jobRep;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data = jobRep.GetAll();
            var model = _mapper.Map<IEnumerable<jobVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(jobVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<job>(model);
                    jobRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = jobRep.GetById(id);
            var model = _mapper.Map<jobVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = jobRep.GetById(id);
            var model = _mapper.Map<jobVM>(data);

            return View(model);
        }

        [HttpPost]
        public IActionResult edit(jobVM model)
        {
            try
            {
                return editjob(model);
            }
            catch
            {
                return View(model);
            }

        }



        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = jobRep.GetById(id);
            var model = _mapper.Map<jobVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(jobVM model)
        {

            try
            {
                var data = _mapper.Map<job>(model);
                jobRep.Delete(data.id);

                return RedirectToAction("Index");


            }
            catch
            {
                return View(model);

            }
        }


        private IActionResult editjob(jobVM model)
        {
            if (ModelState.IsValid)
            {

                var data = _mapper.Map<job>(model);
                jobRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        [HttpGet]
        public JsonResult getAllJobs()
        {
            var data = jobRep.GetAll().Select(o => new { o.id, o.jobName }).ToList();

            return Json(data);
        }


    }
}

companyHR/Controllers/VacationController.cs
using AutoMapper;
using company.BL.Model;
using company.DAL.Repository.Models;
using Microsoft.AspNetCore.Mvc;
using RepositoryUsingEFinMVC.GenericRepository;

namespace companyHR.Controllers
{
    public class VacationController : Controller
    {
        private IGenericRepository<vacation> vacationRep;

        private readonly IMapper _mapper;
        public VacationController(IGenericRepository<vacation> _vacationRep, IMapper mapper)
        {

            this.vacationRep = _vacationRep;
            this._mapper = mapper;
        }
        public IActionResult Index()
        {
            var data = vacationRep.GetAll();
            var model = _mapper.Map<IEnumerable<VacationVM>>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(VacationVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = _mapper.Map<vacation>(model);
                    vacationRep.Insert(data);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }

            }
            catch
            {
                return View(model);

            }

        }
        [HttpGet]
        public IActionResult details(int id)
        {
            var data = vacationRep.GetById(id);
            var model = _mapper.Map<VacationVM>(data);
            return View(model);
        }
        [HttpGet]
        public IActionResult edit(int id)
        {
            var data = vacationRep.GetById(id);
            var model = _mapper.Map<VacationVM>(data);

            return View(model);
        }

        [HttpPost]
        public IActionResult edit(VacationVM model)
        {
            try
            {
                return editVacation(model);
            }
            catch
            {
                return View(model);
            }

        }



        [HttpGet]
        public IActionResult delete(int id)
        {
            var data = vacationRep.GetById(id);
            var model = _mapper.Map<VacationVM>(data);

            return View(model);
        }
        [HttpPost]
        public IActionResult delete(VacationVM model)
        {

            try
            {
                var data = _mapper.Map<vacation>(model);
                vacationRep.Delete(data.id);

                return RedirectToAction("Index");


            }
            catch
            {
                ModelState.AddModelError(string.Empty, "Not Deleted");
                return View(model);

            }
        }




        private IActionResult editVacation(VacationVM model)
        {
            if (ModelState.IsValid)
            {

                var data = _mapper.Map<vacation>(model);
                vacationRep.Update(data);

                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult getAllVacation()
        {
            var data = vacationRep.GetAll().Select(o => new { o.id, o.vacationName }).ToList();

            return Json(data);
        }
    }
}

companyHR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title> @ViewBag.Title</title>






        <!-- Favicon-->
    <link rel="icon" href="~/favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="~/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="~/plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="~/plugins/animate-css/animate.css" rel="stylesheet" />
    <link href="~/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

    <!-- Colorpicker Css -->
    <link href="~/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css" rel="stylesheet" />

    <!-- Dropzone Css -->
    <link href="~/plugins/dropzone/dropzone.css" rel="stylesheet">

    <!-- Multi Select Css -->
@*     <link href="~/plugins/multi-select/css/multi-select.css" rel="stylesheet">
 *@
    <!-- Bootstrap Spinner Css -->
    <link href="~/plugins/jquery-spinner/css/bootstrap-spinner.css" rel="stylesheet">

    <!-- Bootstrap Tagsinput Css -->
    <link href="~/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet">

    <!-- Bootstrap Select Css -->
    <link href="~/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
 
    <!-- noUISlider Css -->
    <link href="~/plugins/nouislider/nouislider.min.css" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="~/css/style.css" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="~/css/themes/all-themes.css" rel="stylesheet" />

    <style>
        .dataTables_length{
            display:none !important;
        }
        .readOnly{
            pointer-events: none;
        }


    </style>
</head>

    <body class="theme-black">
        <!-- Page Loader -->
        <div class="page-loader-wrapper">
            <div class="loader">
                <div class="preloader">
                    <div class="spinner-layer pl-red">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div>
                        <div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
                <p>Please wait...</p>
            </div>
        </div>
        <!-- #END# Page Loader -->
        <!-- Overlay For Sidebars -->
        <div class="overlay"></div>
        <!-- #END# Overlay For Sidebars -->
        <!-- Search Bar -->
    
        <!-- #END# Search Bar -->
        <!-- Top Bar -->
        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-header">
@*                     <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                    <a href="javascript:void(0);" class="bars"></a> *@
                    <a class="navbar-brand" >Company HR</a>
                </div>

            </div>
        </nav>
        <!-- #Top Bar -->
        <section>
            <!-- Left Sidebar -->
            <aside id="leftsidebar" class="sidebar">
                <!-- User Info -->
                <div class="user-info">
                    <div class="image">
                        <img src="images/user.png" width="48" height="48" alt="User" />
                    </div>
                   <div class="info-container">
                        <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ali Shalaby</div>
                      
                    </div> 
                </div>
                <!-- #User Info -->
                <!-- Menu -->
                <div class="menu">
                    <ul class="list">
                        <li class="header">MAIN NAVIGATION</li>
                        <li class="active">
                            <a asp-controller="home" asp-action="index">
                                <i class="material-icons">home</i>
                                <span>Home</span>
                            </a>
                        </li>

                        <li>
                            <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">view_list</i>
                                <span>Main Data</span>
                            </a>
                            <ul class="ml-menu">
                            <li>
                                <a asp-controller="Employees" asp-action="index">
                                    <i class="material-icons"></i>
                                    <span>Employees</span>
                                </a>
                            </li>
                                <li>
                                    <a asp-controller="department" asp-action="index">
                                        <i class="material-icons"></i>
                                    <span>Departments</span>
                                    </a>
                               </li>
                            <li>
                                <a asp-controller="Job" asp-action="index">
                                    <i class="material-icons"></i>
                                    <span>Jobs</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Bonuss" asp-action="index">
                                    <i class="material-icons"></i>
                                    <span>Bonus</span>
                                </a>
                            </li>
                            <li>
                                <a asp-controller="Vacation" asp-action="index">
                                    <i class="material-icons"></i>
                                    <span>Vacations</span>
                                </a>
                            </li>

                            </ul>
                        </li>

                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons ">money</i>
                            <span>Employees Bonus/Deduction</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a asp-controller="EmployeeBonus" asp-action="index">
                                    <i class="material-icons"></i>
                                    <span>Bonus/Deduction</span>
                                </a>
                            </li>


                        </ul>
                    </li>

                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">flight</i>
                            <span>Employees Vacations</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a asp-controller="EmployeesVacation" asp-action="index">
                                    <i class="material-icons"></i>
                                    <span>Employees Vacation</span>
                                </a>
                            </li>


                        </ul>
                    </li>

                </ul>
                </div>
                <!-- #Menu -->
                <!-- Footer -->
            @{
                await Html.RenderPartialAsync("~/views/partialview/partiallayout/footer.cshtml");
            }
                
                <!-- #Footer -->
            </aside>
            <!-- #END# Left Sidebar -->
          
        </section>


    <section class="content">
        <div class="container-fluid">
           
                @RenderBody()
         
    
        </div>
    </section>
      
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="~/plugins/bootstrap/js/bootstrap.js"></script>
    @await RenderSectionAsync("MicrosoftValidation",required:false)


    <!-- Select Plugin Js -->
@*     <script src="~/plugins/bootstrap-select/js/bootstrap-select.js"></script>
 *@
    <!-- Slimscroll Plugin Js -->
    <script src="~/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- Bootstrap Colorpicker Js -->
    <script src="~/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>

    <!-- Dropzone Plugin Js -->
    <script src="~/plugins/dropzone/dropzone.js"></script>

    <!-- Input Mask Plugin Js -->
    <script src="~/plugins/jquery-inputmask/jquery.inputmask.bundle.js"></script>

    <!-- Multi Select Plugin Js -->
@*     <script src="~/plugins/multi-select/js/jquery.multi-select.js"></script>
 *@
    <!-- Jquery Spinner Plugin Js -->
    <script src="~/plugins/jquery-spinner/js/jquery.spinner.js"></script>

    <!-- Bootstrap Tags Input Plugin Js -->
    <script src="~/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>

    <!-- noUISlider Plugin Js -->
    <script src="~/plugins/nouislider/nouislider.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="~/plugins/node-waves/waves.js"></script>

    <!-- Custom Js -->
    <script src="~/js/admin.js"></script>
    <script src="~/js/pages/tables/jquery-datatable.js"></script>
    <script src="~/js/pages/forms/advanced-form-elements.js"></script>

    <!-- Demo Js -->
    <script src="~/js/demo.js"></script>




    @await RenderSectionAsync("ChartJsScripts", required: false)

    @await RenderSectionAsync("DataTabelScripts", required: false)


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>